### ISSUE TITLE
Code Pytorch's model custom class

### ISSUE THREAD

**Issue by heitorc62** [codesnifferai/ai#7]
Our initial idea is to use only the pre-trained model's encoder in order to decide which code-smells the Java class contains.

**Comment by jooag** [comment]
We have a model architecture in mind: CodeT5 encoder with sequence pooling and fully-connected layers to generate classification predictions. After the training, we will evaluate the performance to decide if this architecture is final.

**Comment by heitorc62** [comment]
The performance was great! The next step is to fine-tune the hyperparameters.
